version: '3'
services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app:
    build: .
    command: bundle exec bin/console start $OUTPUT
    volumes:
      - .:/myapp
